definitions:
  steps:
    - step: &build-step
        name: SonarQube analysis
        image: maven:3.3.9
        script:
          - pipe: sonarsource/sonarqube-scan:1.0.0
            variables:
              SONAR_HOST_URL: ${SONAR_HOST_URL}
              SONAR_TOKEN: ${SONAR_TOKEN}

    - step: &make-review
        name: Make Review Step
        script:
          - printenv
          - echo "-------------------------------------------------------------------------"
          - echo ${DOCKERHUB_PASSWORD} | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
          - docker run -d -p 5000:5000 -e REPO_API_TOKEN="${ETENDOBOT_TOKEN}" -e PULL_REQUEST=$BITBUCKET_PR_ID -e PROJECT=$BITBUCKET_REPO_OWNER -e REPO_SLUG=$BITBUCKET_REPO_SLUG -e OPENAI_API_KEY=$OPENAI_API_KEY etendo/code-reviewer:${REVIEWER_VERSION}
          - echo "-------------------------------------------------------------------------"
          - sleep 10s
          - response=$(curl -s -o response.txt -w "%{http_code}" -X GET http://localhost:5000/review/bitbucket)
          - |
            if [ $response -ne 200 ]; then
              echo "API call failed with status code $response"
              echo "Response text:"
              cat response.txt
              exit 1
            fi
          - echo "API call successful with status code $response"
          - echo "Response text:"
          - cat response.txt
        services:
          - docker

    - &build-push-amd64
      name: Build and Push for amd64
      script:
        - |
          if [[ "${BITBUCKET_BRANCH}" == "develop" || "${BITBUCKET_BRANCH}" == "master" ]]; then
            BRANCH_NAME=${BITBUCKET_BRANCH}
          else
            BRANCH_NAME=$(echo ${BITBUCKET_BRANCH} | sed 's/[^a-zA-Z0-9_-]/_/g')
          fi
        - echo ${DOCKERHUB_PASSWORD} | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
        - IMAGE=etendo/dynamic-gradle:${BRANCH_NAME}-amd64
        - docker build --platform linux/amd64 -t ${IMAGE} .
        - docker push ${IMAGE}
      services:
        - docker

    - &build-push-arm64
      name: Build and Push for arm64
      runs-on:
        - self.hosted
        - linux.arm64
      script:
        - |
          if [[ "${BITBUCKET_BRANCH}" == "develop" || "${BITBUCKET_BRANCH}" == "master" ]]; then
            BRANCH_NAME=${BITBUCKET_BRANCH}
          else
            BRANCH_NAME=$(echo ${BITBUCKET_BRANCH} | sed 's/[^a-zA-Z0-9_-]/_/g')
          fi
        - echo ${DOCKERHUB_PASSWORD} | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
        - IMAGE=etendo/dynamic-gradle:${BRANCH_NAME}-arm64
        - docker build --platform linux/arm64/v8 -t ${IMAGE} .
        - docker push ${IMAGE}
      services:
        - docker

    - &create-push-manifest
      name: Create and Push Manifest
      script:
        - |
          if [[ "${BITBUCKET_BRANCH}" == "develop" || "${BITBUCKET_BRANCH}" == "master" ]]; then
            BRANCH_NAME=${BITBUCKET_BRANCH}
          else
            BRANCH_NAME=$(echo ${BITBUCKET_BRANCH} | sed 's/[^a-zA-Z0-9_-]/_/g')
          fi
        - echo ${DOCKERHUB_PASSWORD} | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
        - docker pull etendo/dynamic-gradle:${BRANCH_NAME}-amd64
        - docker pull etendo/dynamic-gradle:${BRANCH_NAME}-arm64
        - docker manifest create etendo/dynamic-gradle:${BRANCH_NAME} etendo/dynamic-gradle:${BRANCH_NAME}-amd64 etendo/dynamic-gradle:${BRANCH_NAME}-arm64
        - docker manifest annotate etendo/dynamic-gradle:${BRANCH_NAME} etendo/dynamic-gradle:${BRANCH_NAME}-amd64 --os linux --arch amd64
        - docker manifest annotate etendo/dynamic-gradle:${BRANCH_NAME} etendo/dynamic-gradle:${BRANCH_NAME}-arm64 --os linux --arch arm64
        - docker manifest push etendo/dynamic-gradle:${BRANCH_NAME}
      services:
        - docker

clone:
  depth: full

pipelines:
  branches:
    feature/ERP-774:
      - step: *build-step
      - parallel:
          - step: *build-push-amd64
          - step: *build-push-arm64
      - step: *create-push-manifest
  pull-requests:
    '**':
      - parallel:
          - step: *make-review
          - step: *build-step