image: maven:3.8.4  # Usa Maven como imagen base para el análisis de SonarQube

clone:
  depth: full

definitions:
  steps:
    # Revisión de código automatizada
    - step: &make-review
        name: Make Review Step
        script:
          - printenv
          - echo "-------------------------------------------------------------------------"
          - echo "${DOCKERHUB_PASSWORD}" | docker login --username "${DOCKERHUB_USERNAME}" --password-stdin
          - docker run -d -p 5000:5000 -e REPO_API_TOKEN="${ETENDOBOT_TOKEN}" -e PULL_REQUEST="${BITBUCKET_PR_ID}" -e PROJECT="${BITBUCKET_REPO_OWNER}" -e REPO_SLUG="${BITBUCKET_REPO_SLUG}" -e OPENAI_API_KEY="${OPENAI_API_KEY}" etendo/code-reviewer:"${REVIEWER_VERSION}"
          - echo "-------------------------------------------------------------------------"
          - sleep 10s
          - response=$(curl -s -o response.txt -w "%{http_code}" -X GET http://localhost:5000/review/bitbucket)
          - |
            if [ "$response" -ne 200 ]; then
              echo "API call failed with status code $response"
              cat response.txt
              exit 1
            fi
          - echo "API call successful with status code $response"
          - cat response.txt
        services:
          - docker

    # Análisis de SonarQube
    - step: &build-step
        name: SonarQube analysis
        script:
          - pipe: sonarsource/sonarqube-scan:1.0.0
            variables:
              SONAR_HOST_URL: ${SONAR_HOST_URL}  # La URL del servidor SonarQube
              SONAR_TOKEN: ${SONAR_TOKEN}  # Token de autenticación de SonarQube
              SONAR_EXCLUDE: node_modules, android, ios  # Exclusión de carpetas innecesarias

    # Construcción y despliegue para amd64
    - step: &build-push-amd
      script:
        - export BRANCH_NAME=$(echo ${BITBUCKET_BRANCH} | sed 's/[^a-zA-Z0-9_-]/_/g')  # Normaliza el nombre de la rama
        - echo "${DOCKERHUB_PASSWORD}" | docker login --username "${DOCKERHUB_USERNAME}" --password-stdin
        - IMAGE=test-lucas/dynamic:${BRANCH_NAME}-amd64
        - docker buildx create --use  # Crea un builder para multi-arquitectura
        - docker buildx inspect --bootstrap  # Verifica que el builder esté listo
        - docker buildx build --platform linux/amd64 -t ${IMAGE} . --push  # Construye y publica la imagen amd64

    # Construcción y despliegue para arm64
    - step: &build-push-arm
      script:
        - export BRANCH_NAME=$(echo ${BITBUCKET_BRANCH} | sed 's/[^a-zA-Z0-9_-]/_/g')  # Normaliza el nombre de la rama
        - echo "${DOCKERHUB_PASSWORD}" | docker login --username "${DOCKERHUB_USERNAME}" --password-stdin
        - IMAGE=test-lucas/dynamic:${BRANCH_NAME}-arm64
        - docker buildx build --platform linux/arm64 -t ${IMAGE} . --push  # Construye y publica la imagen arm64

    - step: &create-push-manifes
      script:
        - export BRANCH_NAME=$(echo ${BITBUCKET_BRANCH} | sed 's/[^a-zA-Z0-9_-]/_/g')  # Normaliza el nombre de la rama
        - echo "${DOCKERHUB_PASSWORD}" | docker login --username "${DOCKERHUB_USERNAME}" --password-stdin
        - docker pull test-lucas/dynamic:${BRANCH_NAME}-amd64
        - docker pull test-lucas/dynamic:${BRANCH_NAME}-arm64
        - docker manifest create test-lucas/dynamic:${BRANCH_NAME} \
            test-lucas/dynamic:${BRANCH_NAME}-amd64 \
            test-lucas/dynamic:${BRANCH_NAME}-arm64  # Crea el manifiesto multi-arquitectura
        - docker manifest annotate test-lucas/dynamic:${BRANCH_NAME} test-lucas/dynamic:${BRANCH_NAME}-amd64 --os linux --arch amd64
        - docker manifest annotate test-lucas/dynamic:${BRANCH_NAME} test-lucas/dynamic:${BRANCH_NAME}-arm64 --os linux --arch arm64
        - docker manifest push test-lucas/dynamic:${BRANCH_NAME}  # Publica el manifiesto

  caches:
    sonar: ~/.sonar

pipelines:
  branches:
    feature/ERP-774:
      - parallel:
          - step: *build-step  # Ejecuta el análisis de SonarQube
          - step: *make-review  # Revisión de código
      - parallel:
          - step: *build-push-amd  # Construye y publica amd64
          - step: *build-push-arm  # Construye y publica arm64
      - step: *create-push-manifes  # Crea y publica el manifiesto

  pull-requests:
    "**":
      - parallel:
          - step: *make-review  # Revisión de código en pull requests
          - step: *build-step  # Análisis de SonarQube en pull requests
