apiVersion: v1
kind: Pod
metadata:
  labels:
    app.kubernetes.io/name: jenkins-node-rx
spec:
  serviceAccountName: default
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst

  volumes:
    - name: rsa-keys
      configMap:
        name: rsa-keys
        defaultMode: 384          # 0600
    - name: dind-storage
      emptyDir: {}                # cache local de imágenes para dind

  containers:
    - name: compiler
      image: etendo/compiler_jenkins:1.0.7
      imagePullPolicy: IfNotPresent
      env:
        - name: DOCKER_HOST
          value: tcp://localhost:2375
      securityContext:
        privileged: true
        runAsUser: 0
      ports:
        - name: ssh
          containerPort: 22
          protocol: TCP
        - name: visualvm
          containerPort: 8000
          protocol: TCP
      resources:
        limits:
          cpu: 2072m
          memory: 4096Mi
        requests:
          cpu: 2072m
          memory: 4096Mi
      volumeMounts:
        - name: rsa-keys
          mountPath: /root/.ssh/
      lifecycle:
        postStart:
          exec:
            command:
              - bash
              - -lc
              - |
                set -e
                apt-get update -y
                command -v docker >/dev/null || apt-get install -y docker.io
                apt-get install -y curl openssl

    - name: dind
      image: docker:25-dind
      securityContext:
        privileged: true
      env:
        - name: DOCKER_TLS_CERTDIR
          value: ""                 # sin TLS dentro del pod
      args:
        - --mtu=1450
        - --storage-driver=overlay2
      resources:
        requests:
          cpu: "4096m"
          memory: "7168Mi"
        limits:
          cpu: "4096m"
          memory: "7168Mi"
      volumeMounts:
        - name: dind-storage
          mountPath: /var/lib/docker
