pipeline {
    options {
        disableConcurrentBuilds()
    }

    environment {
        CONTEXT_NAME        = 'etendo'
        BBDD_SID            = 'etendo'
        BBDD_PORT           = '5432'
        BBDD_SYSTEMUSER     = 'postgres'
        BBDD_SYSTEMPASS     = 'syspass'
        BBDD_USER           = 'tad'
        BBDD_PASSWORD       = 'tad'
        NEXUS_USER          = credentials('nexus-admin-user')
        NEXUS_PASSWORD      = credentials('nexus-admin-passwd')
        GITHUB_USER         = 'etendobot'
        GITHUB_TOKEN        = credentials('github-read-package-token')
        
        USER_ACCESS         = credentials('user-access-commit-bitbucket')
        ACCESS_TOKEN        = credentials('access-token-commit-bitbucket')
        
        OWNER_REPOSITORY    = 'koodu_software'
        REPOSITORY_NAME     = 'com.etendoerp.etendorx'

        EMAIL_ADDRESS       = credentials('email_builds')
        CORE_URL_REPO       = 'https://github.com/etendosoftware/etendo_core'
        RX_URL_REPO         = 'https://github.com/etendosoftware/etendo_rx'
        URL_REPO            = 'https://bitbucket.org/koodu_software/com.etendoerp.etendorx'
        BRANCH_NAME_RX      = 'develop'
        
        COMMIT_AUTHOR_NAME  = sh(returnStdout: true, script: "git log -1 --pretty=format:'%an'").trim()
        COMMIT_AUTHOR_EMAIL = sh(returnStdout: true, script: "git log -1 --pretty=format:'%ae'").trim()

        JAVA_HOME           = '/opt/java/openjdk/'
        CATALINA_HOME       = '${WORKSPACE}/apache-tomcat-8.5.75'
        BUILD_CLASSIC       = true
        DOCKER_HOST         = '/home/jenkins/docker.sock'
        DOCKER_TLS_VERIFY   = 0

        CONTEXT_BUILD       = 'Module Tests'
        STATUSCORE          = '1'

        COMMIT_INPROGRESS_STATUS = 'INPROGRESS'
        COMMIT_SUCCESS_STATUS    = 'SUCCESSFUL'
        COMMIT_FAILED_STATUS     = 'FAILED'
    }

    agent {
        kubernetes {
            inheritFrom 'jenkins-node-rx'
            defaultContainer 'jnlp'
            yaml """
apiVersion: v1
kind: Pod
metadata:
  name: jenkins-node
  namespace: jenkins
  labels:
    app.kubernetes.io/name: jenkins-node
spec:
  containers:
    - name: compiler
      image: etendo/compiler_jenkins:1.0.7
      ports:
        - name: ssh
          containerPort: 22
          protocol: TCP
        - name: visualvm
          containerPort: 8000
          protocol: TCP
      resources:
        limits:
          cpu: 3072m
          memory: 5000Mi
        requests:
          cpu: 3072m
          memory: 5000Mi
      volumeMounts:
        - name: rsa-keys
          mountPath: /root/.ssh/
        - name: docker-sock
          mountPath: /var/run/docker.sock
      lifecycle:
        postStart:
          exec:
            command:
              - bash
              - '-c'
              - >-
                chmod a+x /var/run/docker.sock && rm
                /etc/apt/sources.list.d/pgdg.list || echo 0 && apt update && apt
                install -y curl
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
    - name: postgres
      image: postgres:14
      workingDir: /home/jenkins
      env:
        - name: POSTGRES_PASSWORD
          value: syspass
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
  volumes:
    - name: rsa-keys
      configMap:
        name: rsa-keys
        defaultMode: 384
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst
  serviceAccountName: default
  serviceAccount: default
  securityContext:
    privileged: true

"""
        }
    }
    stages {
        stage ('RX Setup') {
            steps {
                container('compiler') {
                    script {
                        try {
                            echo "Starting Environment tests"
                            sh 'chmod a+x ./pipelines/utils/build-update.sh'
                            sh "./pipelines/utils/build-update.sh ${REPOSITORY_NAME} ${GIT_COMMIT} ${BUILD_NUMBER} ${COMMIT_INPROGRESS_STATUS} \"${CONTEXT_BUILD}\" ${BUILD_URL} \"Starting Build\" ${OWNER_REPOSITORY} ${USER_ACCESS} ${ACCESS_TOKEN}"
                            sh """
                            export DOCKER_HOST=/var/run/docker.sock
                            export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
                            git clone --branch ${BRANCH_NAME_RX} ${RX_URL_REPO}
                            cd etendo_rx
                            cp gradle.properties.template gradle.properties
                            sed -i 's/^githubUser=.*/githubUser=${GITHUB_USER}/' gradle.properties
                            sed -i 's/^githubToken=.*/githubToken=${GITHUB_TOKEN}/' gradle.properties
                            sed -i 's/^grpc.enabled=.*/grpc.enabled=true/' gradle.properties
                            sed -i 's/^data-rest.enabled=.*/data-rest.enabled=true/' gradle.properties
                            mkdir -p modules
                            ./gradlew :setup
                            """
                            env.STATUSRX = "1"
                            echo '...Environment TESTS SUCCESSFUL...'
                        } catch (Exception e) {
                            echo 'Exception occurred: ' + e.toString()
                            echo '...Environment TEST FAILED...'
                            currentBuild.result = 'UNSTABLE'
                            unstable('Environment TESTS FAILED!')
                            env.STATUSTEST = "0"
                            env.STATUSRX = "0"
                        }
                    }
                }
            }
        }
        stage ('Build Environment Etendo Core') {
            when {
                expression {
                    env.BUILD_CLASSIC == "true" && env.STATUSRX == "1"
                }
            }
            steps {
                withCredentials([sshUserPrivateKey(credentialsId: 'my-credentials', keyFileVariable: 'keyfile')]) {
                    withCredentials([usernamePassword(credentialsId: "koodu_credentials", passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
                        sh 'mkdir -p ~/.ssh && ssh-keyscan bitbucket.org >> ~/.ssh/known_hosts'
                        sh """
                        git config user.name "$GIT_USERNAME"
                        git config user.email "$GIT_USERNAME"
                        """

                        // Clone Etendo Core
                        sh 'git clone --branch develop ${CORE_URL_REPO}'
                        // Setup environment
                        sh 'printenv'
                        script {
                            try {
                                echo 'Building Etendo Core'
                                dir("etendo_core") {
                                    sh """
                                    echo -e "context.name=${CONTEXT_NAME}\n
                                    bbdd.sid=${BBDD_SID}\n
                                    bbdd.port=${BBDD_PORT}\n
                                    bbdd.systemUser=${BBDD_SYSTEMUSER}\n
                                    bbdd.systemPassword=${BBDD_SYSTEMPASS}\n
                                    bbdd.user=${BBDD_USER}\n
                                    bbdd.password=${BBDD_PASSWORD}\n
                                    nexusUser=${NEXUS_USER}\n
                                    nexusPassword=${NEXUS_PASSWORD}\n
                                    githubUser=${GITHUB_USER}\n
                                    githubToken=${GITHUB_TOKEN}\n
                                    allow.root=true\n
                                    org.gradle.jvmargs=-Dfile.encoding=UTF-8" > gradle.properties
                                    """
                                    sh './gradlew prepareConfig --info --stacktrace'
                                    sh './gradlew setup --info --stacktrace'
                                    sh './gradlew expandModules --info --stacktrace'
                                    sh """
                                    cd modules
                                    GIT_SSH_COMMAND=\"ssh -i ${keyfile}\" git clone git@bitbucket.org:koodu_software/com.etendoerp.etendorx.git
                                    cd com.etendoerp.etendorx
                                    git checkout ${GIT_COMMIT}
                                    cd ../..
                                    """
                                    sh './gradlew install -PignoreConsistency=true --info --stacktrace'
                                    sh './gradlew smartbuild -PignoreConsistency=true --info --stacktrace'
                                    echo 'Build of Etendo Core Finished'
                                    env.STATUSCORE = "1"
                                    currentBuild.result = 'SUCCESS'
                                }
                            } catch (Exception e) {
                                echo 'Build of Etendo Core FAILED'
                                currentBuild.result = 'FAILED'
                                error('Build Etendo Core FAILED!')
                                env.STATUSCORE = "0"
                            }
                        }
                    }
                }
            }
        }
        stage ('Build Environment Etendo RX') {
            when {
                expression {
                    currentBuild.result == "SUCCESS"
                }
            }
            steps {
                container('compiler') {
                    script {
                        try {
                            echo 'Building Etendo RX'
                            sh 'printenv'
                            sh """
                            export DOCKER_HOST=/var/run/docker.sock
                            export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
                            cd etendo_rx
                            ./gradlew generate.entities --info
                            """
                            echo 'Build of Etendo RX Finished'
                            env.STATUSRX = "1"
                            currentBuild.result = "SUCCESS"
                        } catch (Exception e) {
                            echo 'Build of Etendo RX FAILED'
                            currentBuild.result = 'FAILED'
                            error('Build of Etendo RX FAILED!')
                            env.STATUSRX = "0"
                        }
                    }
                }
            }
        }
        stage ("Run Etendo RX module tests") {
            when {
                expression {
                    currentBuild.result == "SUCCESS"
                }
            }
            steps {
                script {
                    try {
                        env.STATUSTEST = "1"
                        echo "Starting Etendo RX module tests"
                        sh """
                        cd etendo_core
                        ./gradlew test --tests "com.etendoerp.etendorx.*" --info
                        """
                        echo '...ETENDO RX MODULE TESTS SUCCESSFUL...'
                    } catch (Exception e) {
                        echo 'Exception occurred: ' + e.toString()
                        echo '...ETENDO RX MODULE TESTS FAILED...'
                        currentBuild.result = 'UNSTABLE'
                        unstable('ETENDO RX MODULE TESTS FAILED!')
                        env.STATUSTEST = "0"
                    }
                    publishHTML([
                        allowMissing: false,
                        alwaysLinkToLastBuild: false,
                        keepAll: true,
                        reportDir: 'etendo_core/build/reports/tests/test',
                        reportFiles: '*.html',
                        reportName: 'ETENDO RX MODULE TESTS REPORT',
                        reportTitles: ''
                    ])
                }
            }
        }
        stage ("Run Das Tests") {
            when {
                expression {
                    env.STATUSRX == "1"
                }
            }
            steps {
                container("compiler") {
                    script {
                        try {
                            echo "Starting Das tests"
                            sh """
                            export DOCKER_HOST=/var/run/docker.sock
                            export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
                            cd etendo_rx
                            ./gradlew :com.etendorx.das:test --info --tests com.etendorx.das.test.RepositoryTest
                            ./gradlew :com.etendorx.das:test --info --tests com.etendorx.das.test.RestCallTest
                            ./gradlew :com.etendorx.das:test --info --tests com.etendorx.das.test.DefaultFiltersTest
                            ./gradlew :com.etendorx.das:test --info --tests com.etendorx.das.test.eventhandlertest.test.AnnotationTests
                            ./gradlew :com.etendorx.das:test --info --tests com.etendorx.das.unit.BindedRestControllerTest
                            ./gradlew :com.etendorx.das:test --info --tests com.etendorx.das.unit.JsonPathEntityRetrieverDefaultTest
                            ./gradlew :com.etendorx.das:test --info --tests com.etendorx.das.unit.MappingUtilsImplTest
                            ./gradlew :com.etendorx.das:test --info --tests com.etendorx.das.test.DisableEnableTriggersTest
                            ./gradlew :com.etendorx.das:test --info --tests com.etendorx.das.test.FieldMappingRestCallTest
                            ./gradlew :com.etendorx.das:test --info --tests com.etendorx.das.integration.PropertyMetadataTest
                            ./gradlew :com.etendorx.das:test --info --tests com.etendorx.das.unit.BaseDTORepositoryDefaultTests
                            ./gradlew :com.etendorx.das:test --info --tests com.etendorx.das.unit.JsonPathConverterBaseTests
                            ./gradlew :com.etendorx.das:test --info --tests com.etendorx.entities.mapper.lib.JsonPathEntityRetrieverBaseTests
                            """
                            echo '...DAS TESTS SUCCESSFUL...'
                        } catch (Exception e) {
                            echo 'Exception occurred: ' + e.toString()
                            echo '...DAS TEST FAILED...'
                            currentBuild.result = 'UNSTABLE'
                            unstable('DAS TESTS FAILED!')
                            env.STATUSTEST = "0"
                        }
                        if(fileExists('etendo_rx/modules_core/com.etendorx.das/build/reports/tests/test')) {
                            publishHTML([
                                allowMissing: false,
                                alwaysLinkToLastBuild: false,
                                keepAll: true,
                                reportDir: 'etendo_rx/modules_core/com.etendorx.das/build/reports/tests/test',
                                reportFiles: '*.html',
                                reportName: 'DAS TESTS REPORT',
                                reportTitles: ''
                            ])
                        }
                    }
                }
            }
        }
    }
    post {
        fixed {
            mail to: EMAIL_ADDRESS,
            subject: "✅ FIXED - ${currentBuild.fullDisplayName}",
            mimeType: "text/html",
            body: """
            <html>
                <head>
                    <style>
                        body { font-family: 'Arial', sans-serif; }
                        .header { font-size: 16px; font-weight: bold; color: #333; }
                    </style>
                </head>
                <body>
                    <p><em>${new Date()}</em></p>
                    <p>__________________________________________________________</p>

                    <h2 class="header">✅ ERRORS FIXED ✅ ✅</h2>

                    <p>
                        <strong>Commit:</strong> <a href="${URL_REPO}/commits/${env.GIT_COMMIT}">${URL_REPO}/commits/${env.GIT_COMMIT}</a><br />
                        <strong>Author:</strong> ${COMMIT_AUTHOR_NAME} (${COMMIT_AUTHOR_EMAIL})
                    </p>
                    <p>
                        The build has failed unexpectedly.<br />
                        💡 This build was on an Full Etendo (CORE and RX) build environment based on RX module commit.<br />
                        For more information on the failing run, visit:<br />
                        <a href="${env.BUILD_URL}">${env.BUILD_URL}</a>
                    </p>
                    <p>__________________________________________________________</p>
                </body>
            </html>
            """
        }
        failure {
            script {
                sh 'chmod a+x ./pipelines/utils/build-update.sh'
                sh './pipelines/utils/build-update.sh $REPOSITORY_NAME $GIT_COMMIT $BUILD_NUMBER $COMMIT_INPROGRESS_STATUS \"${CONTEXT_BUILD}\" $BUILD_URL "Starting build" $OWNER_REPOSITORY $USER_ACCESS $ACCESS_TOKEN'
                echo "Failed Build Environments"
            }
            cleanWs deleteDirs: true
            mail to: EMAIL_ADDRESS,
            subject: "⛔ ERROR - ${currentBuild.fullDisplayName}",
            mimeType: "text/html",
            body:  """
            <html>
                <head>
                    <style>
                        body { font-family: 'Arial', sans-serif; }
                        .header { font-size: 16px; font-weight: bold; color: #333; }
                    </style>
                </head>
                <body>
                    <p><em>${new Date()}</em></p>
                    <p>__________________________________________________________</p>

                    <h2 class="header">🚫 BUILD FAILED 🚫</h2>

                    <p>
                        <strong>Commit:</strong> <a href="${URL_REPO}/commits/${env.GIT_COMMIT}">${URL_REPO}/commits/${env.GIT_COMMIT}</a><br />
                        <strong>Author:</strong> ${COMMIT_AUTHOR_NAME} (${COMMIT_AUTHOR_EMAIL})
                    </p>
                    <p>
                        The build has failed unexpectedly.<br />
                        💡 This build was on an Full Etendo (CORE and RX) build environment based on RX module commit.<br />
                        To more information on the failing run visit:<br />
                        <a href="${env.BUILD_URL}">${env.BUILD_URL}</a>
                    </p>
            __________________________________________________________
            """
        }
        unstable {
            script {
                sh 'chmod a+x ./pipelines/utils/build-update.sh'
                sh './pipelines/utils/build-update.sh $REPOSITORY_NAME $GIT_COMMIT $BUILD_NUMBER $COMMIT_INPROGRESS_STATUS \"${CONTEXT_BUILD}\" $BUILD_URL "Starting build" $OWNER_REPOSITORY $USER_ACCESS $ACCESS_TOKEN'
                echo "Failed Test"
            }
            cleanWs deleteDirs: true
            mail to: EMAIL_ADDRESS,
            subject: "⚠️ TESTS FAILED - ${currentBuild.fullDisplayName}",
            mimeType: "text/html",
            body: """
            <html>
                <head>
                    <style>
                        body { font-family: 'Arial', sans-serif; }
                        .header { font-size: 16px; font-weight: bold; color: #333; }
                    </style>
                </head>
                <body>
                    <p><em>${new Date()}</em></p>
                    <p>__________________________________________________________</p>

                    <h2 class="header">🚨 BUILD UNSTABLE 🚨</h2>

                    <p>
                        <strong>Commit:</strong> <a href="${URL_REPO}/commits/${env.GIT_COMMIT}">${URL_REPO}/commits/${env.GIT_COMMIT}</a><br />
                        <strong>Author:</strong> ${COMMIT_AUTHOR_NAME} (${COMMIT_AUTHOR_EMAIL})
                    </p>
                    <p>
                        Tests have been detected that have failed in Etendo RX module and/or DAS test.<br />
                        💡 These tests were run on a Postgres database environment.<br />
                        To more information on the failing run visit:<br />
                        <a href="${env.BUILD_URL}">${env.BUILD_URL}</a>
                    </p>
            __________________________________________________________
            """
        }
        success {
            script {
                sh 'chmod a+x ./pipelines/utils/build-update.sh'
                sh './pipelines/utils/build-update.sh $REPOSITORY_NAME $GIT_COMMIT $BUILD_NUMBER $COMMIT_INPROGRESS_STATUS \"${CONTEXT_BUILD}\" $BUILD_URL "Starting build" $OWNER_REPOSITORY $USER_ACCESS $ACCESS_TOKEN'
                echo "Successful Test"
            }
            cleanWs deleteDirs: true
        }
    }
}