services:
  obconnsrv:
    image: etendo/dynamic-gradle:1.1.0
    ports:
      - "8101:8101"
      - "5025:8000"
    environment:
      - DEPENDENCIES=com.etendorx.integration:obconn-srv:1.0.1
      - REPO_URL=${ETENDORX_REPOSITORY_URL}
      - REPO_USER=${ETENDORX_REPOSITORY_USER}
      - REPO_PASSWORD=${ETENDORX_REPOSITORY_PASSWORD}
      - CONFIG_SERVER_URL=${ETENDORX_CONFIG_SERVER_URL}
      - TASK=downloadJar
      # --- OpenTelemetry ---
      - ENABLE_OPEN_TELEMETRY=false
      - OTEL_SERVICE_NAME=obconnsrv
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318
    networks:
      - etendo
    volumes:
      - obconnsrv:/root/.gradle
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://localhost:8101/actuator/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 60

  worker:
    image: etendo/dynamic-gradle:1.1.0
    ports:
      - "8102:8102"
      - "5026:8000"
    environment:
      - DEPENDENCIES=com.etendorx.integration:obconn-wrk:1.0.1
      - REPO_URL=${ETENDORX_REPOSITORY_URL}
      - REPO_USER=${ETENDORX_REPOSITORY_USER}
      - REPO_PASSWORD=${ETENDORX_REPOSITORY_PASSWORD}
      - CONFIG_SERVER_URL=${ETENDORX_CONFIG_SERVER_URL}
      - TASK=downloadJar
      # --- OpenTelemetry ---
      - ENABLE_OPEN_TELEMETRY=false
      - OTEL_SERVICE_NAME=worker
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4318
    networks:
      - etendo
    volumes:
      - worker:/root/.gradle
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://localhost:8102/actuator/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 60

volumes:
    obconnsrv:
    worker:
