services:
  kafka-ui:
    image: redpandadata/console:v3.1.3
    ports:
      - 9094:8080
    environment:
      - KAFKA_BROKERS=kafka:9092
      - CONNECT_BOOTSTRAP_SERVERS=connect:8083
    networks:
      - etendo
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
    restart: on-failure:5
    depends_on:
      - kafka
      - connect

  jaeger:
    image: cr.jaegertracing.io/jaegertracing/jaeger:2.8.0
    ports:
      - "16686:16686"   # Jaeger UI
      - "4317:4317"     # OTLP gRPC
      - "4318:4318"     # OTLP HTTP
      - "5778:5778"     # health-check & debug
      - "9411:9411"     # Zipkin HTTP
    command:
      - "--config"
      - "/jaeger/config.yaml"
    networks:
      - etendo
    volumes:
      - ${VOLUMES_PATH}/jaeger/config.yaml:/jaeger/config.yaml
