services:
  kafka-ui:
    image: redpandadata/console:v3.1.3
    ports:
      - 9094:8080
    environment:
      - KAFKA_BROKERS=kafka:9092
      - CONNECT_BOOTSTRAP_SERVERS=connect:8083
    networks:
      - etendo
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 128M
    restart: on-failure:5
    depends_on:
      - kafka
      - connect

  jaeger:
    image: cr.jaegertracing.io/jaegertracing/jaeger:2.8.0
    ports:
      - "16686:16686"   # Jaeger UI
      - "4317:4317"     # OTLP gRPC
      - "4318:4318"     # OTLP HTTP
      - "5778:5778"     # Remote Sampling (HTTP /sampling)
      - "9411:9411"     # Zipkin HTTP
      - "13133:13133"   # Management: health (/status)
    command:
      - "--config"
      - "/jaeger/config.yaml"
    networks:
      - etendo
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
    volumes:
      - ${VOLUMES_PATH}/jaeger/config.yaml:/jaeger/config.yaml

  jaeger-health:
    image: curlimages/curl:8.15.0
    command: ["sh", "-c", "sleep infinity"]
    depends_on:
      - jaeger
    networks:
      - etendo
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://jaeger:13133/status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
