services:
  kafka-ui:
    image: redpandadata/console
    ports:
      - 9094:8080
    environment:
      - KAFKA_BROKERS=kafka:9092
      - CONNECT_BOOTSTRAP_SERVERS=connect:8083
    networks:
      - etendo
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
    restart: on-failure:5
    depends_on:
      - kafka
      - connect

  jaeger:
    image: jaegertracing/all-in-one:1.70.0
    ports:
      - "4317:4317"
      - "4318:4318"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
      - "16686:16686"
    environment:
      COLLECTOR_ZIPKIN_HTTP_ENABLED: true
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
      JAEGER_COLLECTOR_ZIPKIN_HTTP_PORT: 9411
      JAEGER_AGENT_HOST: jaeger
      JAEGER_AGENT_PORT: 5775
      JAEGER_DISABLED: false
      COLLECTOR_OTLP_ENABLED: true
      AEGER_OTLP_HTTP_PORT: 4318
      METRICS_STORAGE_TYPE: prometheus
    networks:
      - etendo
