services:
  config:
    depends_on:
      db:
        condition: service_healthy
    container_name: config
    image: etendo/dynamic-gradle:latest
    ports:
      - "8888:8888"
    volumes:
      - ../../build/rxconfig:/rxconfig
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCHLOCATIONS=file:///rxconfig
      - SPRING_PROFILES_ACTIVE=native
      - DEPENDENCIES=com.etendorx:configserver:${ETENDORX_VERSION}
      - REPO_URL=${ETENDORX_REPOSITORY_URL}
      - REPO_USER=${ETENDORX_REPOSITORY_USER}
      - REPO_PASSWORD=${ETENDORX_REPOSITORY_PASSWORD}
      - TASK=downloadJar
    networks:
      - etendo
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://localhost:8888/actuator/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 60

  das:
    depends_on:
      db:
        condition: service_healthy
      config:
        condition: service_healthy
    container_name: das
    image: etendo/dynamic-das:latest
    ports:
      - "8092:8092"
      - "5005:5005"
    environment:
      - DEPENDENCIES=com.etendorx:das:${ETENDORX_VERSION}
      - REPO_URL=${REPOSITORY_URL}
      - REPO_USER=${REPOSITORY_USER}
      - REPO_PASSWORD=${REPOSITORY_PASSWORD}
      - CONFIG_SERVER_URL=http://config:8888
      - TASK=downloadJar
      - DEBUG_PORT=5005
    networks:
      - etendo
    volumes:
      - ./volumes/das/gradle-cache:/root/.gradle
      - ./volumes/das/app:/app/
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://localhost:8888/actuator/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 60
  auth:
    depends_on:
      db:
        condition: service_healthy
      config:
        condition: service_healthy
    container_name: auth
    image: etendo/dynamic-gradle:latest
    ports:
      - "8094:8094"
    environment:
      - DEPENDENCIES=com.etendorx:auth:${ETENDORX_VERSION}
      - REPO_URL=${REPOSITORY_URL}
      - REPO_USER=${REPOSITORY_USER}
      - REPO_PASSWORD=${REPOSITORY_PASSWORD}
      - CONFIG_SERVER_URL=http://config:8888
      - TASK=downloadJar
    networks:
      - etendo
    volumes:
      - ./volumes/auth/gradle-cache:/root/.gradle
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://localhost:8888/actuator/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 60
networks:
  etendo:
