services:
  kafka:
    image: bitnami/kafka:4.0.0
    ports:
      - "9092:9092"
      - "9093:9093"
      - "29092:29092"
      - "9997:9997"
    environment:
      KAFKA_CFG_PROCESS_ROLES: "controller,broker"
      KAFKA_CFG_NODE_ID: "1"
      KAFKA_CLUSTER_ID: "1fAy-_QvR3yHBXb3_K0-Mg"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      # --- Configuration for Kafka Broker ---
      KAFKA_CFG_LISTENERS: CONTROLLER://0.0.0.0:9093,INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:29092
      # For INTERNAL connections (inside the docker network) use the "kafka" hostname and 9092 port
      # For EXTERNAL connections (outside the docker network) use "localhost" hostname and 29092 port
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      ENV KAFKA_METADATA_LOG_SEGMENT_MS: 15000
      ENV KAFKA_METADATA_MAX_RETENTION_MS: 60000
      ENV KAFKA_METADATA_LOG_MAX_RECORD_BYTES_BETWEEN_SNAPSHOTS: 2800
      # --- JMX opcional ---
      JMX_PORT: "9997"
      KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.net.preferIPv4Stack=true -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.rmi.port=9997"
      # Optimizaciones de la JVM para Kafka
      KAFKA_HEAP_OPTS: "-Xms512M -Xmx512M"
    networks:
      - etendo
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
    volumes:
      - ${VOLUMES_PATH}/kafka_data:/bitnami

  connect:
    image: debezium/connect:2.7.1.Final
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: '1'
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses
      KAFKA_HEAP_OPTS: "-Xms512M -Xmx512M"
    depends_on:
      - kafka
    networks:
      - etendo
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G

  asyncprocess:
    env_file: ".env"
    build:
      context: .
      dockerfile: dynamic/Dockerfile
      args:
        - DEPENDENCIES=com.etendorx:asyncprocess:${ETENDORX_VERSION}
        - REPO_URL=${ETENDORX_REPOSITORY_URL}
        - REPO_USER=${ETENDORX_REPOSITORY_USER}
        - REPO_PASSWORD=${ETENDORX_REPOSITORY_PASSWORD}
        - SPRING_PROFILES_ACTIVE=native
        - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCHLOCATIONS=file:///rxconfig
        - CONFIG_SERVER_URL=
        - DEBUG_MODE=true
    depends_on:
      config:
        condition: service_healthy
    ports:
      - "8099:8099"
      - "${ASYNCPROCESS_DEBUG_PORT:-5024}:8000"
    environment:
      - DEPENDENCIES=com.etendorx:asyncprocess:${ETENDORX_VERSION}
      - REPO_URL=${ETENDORX_REPOSITORY_URL}
      - REPO_USER=${ETENDORX_REPOSITORY_USER}
      - REPO_PASSWORD=${ETENDORX_REPOSITORY_PASSWORD}
      - CONFIG_SERVER_URL=${ETENDORX_CONFIG_SERVER_URL}
      - TASK=downloadJar
      # ---- Debugging & JVM ----
      - DEBUG_PORT=${ASYNCPROCESS_DEBUG_PORT:-5024}
      - DEBUG_MODE=${ASYNCPROCESS_DEBUG_MODE:-false}
      - DISABLE_DEBUG=${ASYNCPROCESS_DISABLE_DEBUG:-false}
      - JAVA_OPTS=-XX:MaxRAMPercentage=75.0 -XX:+UseG1GC ${ASYNCPROCESS_JAVA_OPTS:-}
      - GRADLE_FLAGS=${ASYNCPROCESS_GRADLE_FLAGS:-}
      # --- OpenTelemetry ---
      - ENABLE_OPEN_TELEMETRY=${OTEL_ASYNCPROCESS_ENABLE:-false}
      - OTEL_SERVICE_NAME=${OTEL_ASYNCPROCESS_NAME:-asyncprocess}
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_ASYNCPROCESS_OTLP_ENDPOINT:-http://jaeger:4318}
      - OTEL_EXPORTER_OTLP_PROTOCOL=${OTEL_ASYNCPROCESS_OTLP_PROTOCOL:-http/protobuf}
      - OTEL_METRICS_EXPORTER=${OTEL_ASYNCPROCESS_METRICS_EXPORTER:-none}
      - OTEL_LOGS_EXPORTER=${OTEL_ASYNCPROCESS_LOGS_EXPORTER:-none}
      - OTEL_TRACES_EXPORTER=${OTEL_ASYNCPROCESS_TRACES_EXPORTER:-otlp}
      - OTEL_EXPORTER_OTLP_TIMEOUT=${OTEL_ASYNCPROCESS_EXPORTER_OTLP_TIMEOUT:-10000}
    networks:
      - etendo
    # Se eliminaron las referencias a async_vol
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://localhost:8099/actuator/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 60
    deploy:
      resources:
        limits:
          memory: 256M

volumes:
  async_vol:

