services:
  kafka:
    image: bitnami/kafka:4.0.0
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
      - "9093:9093"
      - "9997:9997"
    environment:
      KAFKA_CFG_PROCESS_ROLES: "controller,broker"
      KAFKA_CFG_NODE_ID: "1"
      KAFKA_CLUSTER_ID: "1fAy-_QvR3yHBXb3_K0-Mg"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"

      KAFKA_CFG_LISTENERS: CONTROLLER://0.0.0.0:9093,INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092

      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092

      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT

      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      #KAFKA_CFG_NUM_PARTITIONS: "50"
      # --- JMX opcional ---
      JMX_PORT: "9997"
      KAFKA_JMX_OPTS: -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.net.preferIPv4Stack=true -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.rmi.port=9997
    networks:
      - etendo
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G
    volumes:
        - ${VOLUMES_PATH}/kafka_data:/bitnami

  connect:
    image: debezium/connect:2.7.1.Final
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: kafka:29092
      GROUP_ID: '1'
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses
    depends_on:
      - kafka
    networks:
      - etendo

  kafka-ui:
    image: redpandadata/console
    ports:
      - 9094:8080
    environment:
      - KAFKA_BROKERS=kafka:29092
      - CONNECT_BOOTSTRAP_SERVERS=connect:8083
    networks:
      - etendo
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

volumes:
  async_vol:
  kafka_data:
