services:
  obconnsrv:
    image: etendo/dynamic-gradle:1.0.0
    ports:
      - "8101:8101"
      - "5025:8000"
    environment:
      - DEPENDENCIES=com.etendorx.integration:obconn-srv:1.0.1
      - REPO_URL=${ETENDORX_REPOSITORY_URL}
      - REPO_USER=${ETENDORX_REPOSITORY_USER}
      - REPO_PASSWORD=${ETENDORX_REPOSITORY_PASSWORD}
      - CONFIG_SERVER_URL=${ETENDORX_CONFIG_SERVER_URL}
      - TASK=downloadJar
    networks:
      - etendo
    volumes:
      - obconnsrv:/root/.gradle

  worker:
    image: etendo/dynamic-gradle:1.0.0
    ports:
      - "5026:8000"
      - "8102:8102"
    environment:
      - DEPENDENCIES=com.etendorx.integration:obconn-wrk:1.0.1
      - REPO_URL=${ETENDORX_REPOSITORY_URL}
      - REPO_USER=${ETENDORX_REPOSITORY_USER}
      - REPO_PASSWORD=${ETENDORX_REPOSITORY_PASSWORD}
      - CONFIG_SERVER_URL=${ETENDORX_CONFIG_SERVER_URL}
      - TASK=downloadJar
    networks:
      - etendo
    volumes:
      - worker:/root/.gradle

volumes:
    obconnsrv:
    worker:
